"""Migration for product-WIP

Revision ID: 9a9da8c4cb3a
Revises: 44c13d40bcad
Create Date: 2024-03-07 14:30:02.425139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9da8c4cb3a'
down_revision = '44c13d40bcad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
